### PR TITLE
adapted reward logic to 3DotsHub version

### PR DESCRIPTION
**Pull request by kuegi**
thx to @3DotsHub for the idea

### CODE REVIEW

**Comment by 3DotsHub** [comment]
@kuegi thank you for implementing, its definitely a cleaner approach. I will go through this feature-branch.

**Comment by 3DotsHub** [comment]
### @kuegi Fix in lockup function, by subtracting **totalWithdrawalFunds**
```
require(lockupAmount + totalDepositFunds - **totalWithdrawalFunds** <= fundsDepositCap, "Fund deposit cap is reached");
```

**Comment by kuegi** [comment]
> I cloned your repo and if its okay for you, i will contribute on the branch. At the moment, i give it a clean up and checking functionality.
> 
> Because so far i understand in Solidity, mapping is not similar to array type and does not hold items. I guess it makes it quite hard to extract all "depositors" addresses due to mapping, scanning the blockchain for events would be required.
> 
> We should change it to batch type mapping:
> 
> ```
> From:
> mapping(address => LockEntry[]) public investments;
> 
> To:
> LockEntry[] public lockBatch;
> mapping(address => uint256[]) investBatches;
> ```
> 
> I guess, this would be more efficient, because the array would hold items instead of an "unlimited" mapping of addresses. Also improves interacting with the SmartContract for dev's, bots, dapps, ...

mapping also holds the elements. In your code its just mixed between an array and a mapping. Doesn't make it more efficient. IMHO the version with just the mapping is far easier to read and maintain.

**Comment by 3DotsHub** [comment]
> > I cloned your repo and if its okay for you, i will contribute on the branch. At the moment, i give it a clean up and checking functionality.
> > Because so far i understand in Solidity, mapping is not similar to array type and does not hold items. I guess it makes it quite hard to extract all "depositors" addresses due to mapping, scanning the blockchain for events would be required.
> > We should change it to batch type mapping:
> > ```
> > From:
> > mapping(address => LockEntry[]) public investments;
> > 
> > To:
> > LockEntry[] public lockBatch;
> > mapping(address => uint256[]) investBatches;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I guess, this would be more efficient, because the array would hold items instead of an "unlimited" mapping of addresses. Also improves interacting with the SmartContract for dev's, bots, dapps, ...
> 
> mapping also holds the elements. In your code its just mixed between an array and a mapping. Doesn't make it more efficient. IMHO the version with just the mapping is far easier to read and maintain.

Source: https://ethereum.stackexchange.com/questions/15337/can-we-get-all-elements-stored-in-a-mapping-in-the-contract

_"Mappings do not store their keys, only the value which is stored at the state memory address calculated by a sha3 hash of the the key itself. Any lookup into a mapping has to provide that original key or be able to calculate it.

This means that a contract has no way of discovering mapped data without assistance which can lead to orphaned data bloating the state database, particularly after a contract is selfdestructed."_

Just to let you know. Mapping does not store the key and as far I know, a mix of mapping and array for storing keys, is the way to go in Solidity. How would you get all depositors addresses via SC? 🤔

**Comment by kuegi** [comment]
> > > I cloned your repo and if its okay for you, i will contribute on the branch. At the moment, i give it a clean up and checking functionality.
> > > Because so far i understand in Solidity, mapping is not similar to array type and does not hold items. I guess it makes it quite hard to extract all "depositors" addresses due to mapping, scanning the blockchain for events would be required.
> > > We should change it to batch type mapping:
> > > ```
> > > From:
> > > mapping(address => LockEntry[]) public investments;
> > > 
> > > To:
> > > LockEntry[] public lockBatch;
> > > mapping(address => uint256[]) investBatches;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I guess, this would be more efficient, because the array would hold items instead of an "unlimited" mapping of addresses. Also improves interacting with the SmartContract for dev's, bots, dapps, ...
> > 
> > 
> > mapping also holds the elements. In your code its just mixed between an array and a mapping. Doesn't make it more efficient. IMHO the version with just the mapping is far easier to read and maintain.
> 
> Source: https://ethereum.stackexchange.com/questions/15337/can-we-get-all-elements-stored-in-a-mapping-in-the-contract
> 
> _"Mappings do not store their keys, only the value which is stored at the state memory address calculated by a sha3 hash of the the key itself. Any lookup into a mapping has to provide that original key or be able to calculate it.
> 
> This means that a contract has no way of discovering mapped data without assistance which can lead to orphaned data bloating the state database, particularly after a contract is selfdestructed."_
> 
> Just to let you know. Mapping does not store the key and as far I know, a mix of mapping and array for storing keys, is the way to go in Solidity. How would you get all depositors addresses via SC? 🤔

ok yes, keys are not stored. In the current way you can get all depositors by reading the deposit events. We can also store the address in an array, but this data is not needed by the SC itself as it should not iterate over it anyway.

**Comment by kuegi** [comment]
@3DotsHub I merged it in so that others don't review the old branch. will continue working from master.

**Pull request merged**
